#!/usr/bin/env sh

# Prevents freezing simple-bar upon Yabai restart
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

yabai -m config external_bar all:32:0 \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_shadow float \
    window_opacity on \
    window_opacity_duration 0.2 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.8 \
    insert_feedback_color 0xff9dd274 \
    split_ratio 0.50 \
    auto_balance off \
    mouse_modifier cmd \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    \
    top_padding 15 \
    bottom_padding 15 \
    left_padding 15 \
    right_padding 15 \
    window_gap 15

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Antinote|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# Pin app to specific spaces
yabai -m rule --add app="XLD$" space=^5

# We want special behavior if we have one window on a display
#yabai -m signal --add event=window_created action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=window_moved action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=window_destroyed action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=application_launched action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=application_terminated action="~/.config/yabai/single_window.sh"

# Testing simple-bar-server refreshes
yabai -m signal --add event=window_focused action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows when focused application changes"
yabai -m signal --add event=window_resized action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows when a window is resized"
yabai -m signal --add event=window_destroyed action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-ba spaces & windows when an application window is closed"
yabai -m signal --add event=space_changed action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows on space change"
yabai -m signal --add event=display_changed action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows on display focus change"
yabai -m signal --add event=window_title_changed action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows when current window title changes"
yabai -m signal --add event=space_destroyed action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows on space removal"
yabai -m signal --add event=space_created action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows on space creation"
yabai -m signal --add event=application_activated action="curl http://localhost:7776/yabai/spaces/refresh && curl http://localhost:7776/yabai/windows/refresh" label="Refresh simple-bar spaces & windows when application is activated"
yabai -m signal --add event=display_added action="curl http://localhost:7776/yabai/displays/refresh" label="Refresh simple-bar displays when a new dispay is added"
yabai -m signal --add event=display_removed action="curl http://localhost:7776/yabai/displays/refresh" label="Refresh simple-bar displays when a dispay is removed"
yabai -m signal --add event=display_moved action="curl http://localhost:7776/yabai/displays/refresh" label="Refresh simple-bar displays when a dispay is moved"

echo "yabai configuration loaded.."
