#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


yabai -m config external_bar               all:47:0       \
                mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             on             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.8            \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             cmd            \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                15             \
                bottom_padding             15             \
                left_padding               15             \
                right_padding              15             \
                window_gap                 15

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

# We want special behavior if we have one window on a display
#yabai -m signal --add event=window_created action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=window_moved action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=window_destroyed action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=application_launched action="~/.config/yabai/single_window.sh"
#yabai -m signal --add event=application_terminated action="~/.config/yabai/single_window.sh"

echo "yabai configuration loaded.."
