
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g @logging-path "/tmp/tmux"

# Reload tmux config
unbind r
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Start in fish shell
set -g default-command fish

# Set ctrl-s combo as leader
set -g prefix C-s

# Mouse
set -g mouse on
bind-key -n WheelUpPane if -F '#{alternate_on}' 'send-keys Up' 'if -F "#{mouse_any_flag}" "send -M" "copy-mode -e; send-keys -M"'
bind-key -n WheelDownPane if -F '#{alternate_on}' 'send-keys Down' 'send-keys -M'

set -g default-terminal "screen-256color"
set -ag terminal-overrides ',xterm-256color*:RGB'

# Copy paste issues.  Not sure if any of these are needed.
set -g allow-passthrough on

# don't exit from tmux when closing a session
set -g detach-on-destroy off

# Copy Mode Settings
# Copy - activate with <leader-[>
setw -g mode-keys vi
# bind -n C-j copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.
# bind-key -T copy-mode-vi '/' send-key ?

# Additional key bindings
bind-key j command-prompt -p "send pane to:" "join-pane -t '%%'" # Enter color before window number [ex. :0]

# Set new panes to open in current directory
bind-key c new-window -c "#{pane_current_path}"
bind-key v split-window -c "#{pane_current_path}"
bind-key g split-window -h -c "#{pane_current_path}"


# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_maroon}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_peach}]#{?window_zoomed_flag,  zoom ,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_red}]#{?pane_in_mode,  copy ,}"

# status right look and feel
set -g status-right-length 120
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_overlay_0},none]│"
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_blue}] 󱇶 #(gcloud config list --format='value[](core.account)') "
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_blue}][#(gcloud config list --format='value[](core.project)')] "
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_overlay_0},none]│"
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_green}] 󱃾 #(kubectl config view --minify --output 'jsonpath={.current-context}'):"
set -ga status-right "#[bg=#{@thm_bg}, fg=#{@thm_green}][#(kubectl config view --minify --output 'jsonpath={..namespace}')] "

set -g status-position top
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-border-status top
set -wgF pane-border-style "fg=#{@thm_red}"
setw -g pane-border-format " #[fg=white,bg=default]#{pane_index}:#{pane_title} "
set -wgF pane-active-border-style "fg=#{@thm_yellow}"
setw -g pane-border-lines single
setw -g pane-border-indicators arrows


# Auto tpm install -> no worky
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux-tea'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
